### ISSUE TITLE
Upscale U3 button not being clicked

### ISSUE THREAD

**Issue by jasoncslaughter** [Draym/discord-puppet#5]
I was thrilled to find this fantastic library! For the most part, it is working perfectly... But I am having one strange issue. It will not upscale the third image. Here is my code:

```
export const midjourney = async (prompts: string[], path) => {
  const config: Option = options(
    username,
    password,
    [],
    undefined,
    true,
    false,
    5000,
    5000,
    5000
  );
  const puppet = new MidjourneyPuppet(config);
  await puppet.start();
  await puppet.clickServer(server);
  await puppet.clickChannel(channel);

  for (let i = 0; i < prompts.length; i++) {
    const msg = await puppet.imagine(prompts[i]);
    for (let z = 1; z < 5; z++) {
      const enlargeType: EnlargeType = `U${z}` as EnlargeType;
      const subImage = await puppet.imageEnlarge(msg.messageId, enlargeType);
      await downloadImage(
        subImage.imageUrl!,
        `${path}/${enlargeType}_${i}.png`
      );
    }
  }

  await puppet.shutdown();
};
````

As you can see, I increased all the delays to 5 seconds to avoid any time delay-related issues. And I checked the code to make sure there wasn't a problem with the enums or anything like that. It just isn't properly clicking the U3 button in Discord. Has anyone else had that issue?

**Comment by Draym** [comment]
Hi! thanks for testing out this project

Can you confirm it worked for U1, U2, U4 ? i would like to confirm first that only U3 doesn't work on your side.

**Comment by jasoncslaughter** [comment]
> Can you confirm it worked for U1, U2, U4 ? i would like to confirm first that only U3 doesn't work on your side.

It works for U1, U2, and U4. It is only U3 that is not working.

I am running it in the order of U1, U2, U3, and then U4 - I haven't tested in another order, so I don't know if is failing based on it being U3, or it being the 3rd.

**Comment by Draym** [comment]
I couldn't reproduce your issue in my local. it works just fine as you can see in the screenshot. [screenshot](https://cdn.discordapp.com/attachments/1074234231175262248/1143617156886573106/Screenshot_2023-08-22_at_20.45.16.png)

can it be due to a connection issue? where the program clicks in the UI before the button is fully loaded

**Comment by akwin1234** [comment]
@Draym Draym

i am having same issue.. in my case randomly U1 to U4 something is failing.. and other's output is coming in other one's output


`import 'dotenv/config'
import Option from "../src/interfaces/option.interface"
import {buildOptions} from "../src/utils/options"
import MidjourneyPuppet from "../src/midjourney.puppet"
import {EnlargeType} from "../src/enums"
import Language from "../src/enums/language";
import express from "express";
import bodyParser from "body-parser";

/** TEST script that execute midjourney puppet **/
let client, msg1;

const app = express();
app.use(bodyParser.json());

async function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

async function login(){
    const config: Option = buildOptions({
        username: "kyleeplageman@gmail.com",
        password: "bMXJ4em6gKr82JN",
        userDataDir: "/home/tmp/images/",//process.env.DISCORD_USER_DATA_DIR,
        language: Language.EN
    })
    client = new MidjourneyPuppet(config)
    await client.start()
    await client.clickServer("My AI Art")
    await client.clickChannel("general")

    msg1 = await client.info()
    console.log("Midjourney Account info: ", msg1)


}
async function execute(prompt) {
    function loading(url: string) {
        console.log("LOADING: ", url)
    }
    let images = []
    const baseimage = await client.imagine(prompt);
    console.log("Images: ", baseimage)
    await sleep(3000)
    const msg1 = await client.imageEnlarge(baseimage.messageId, EnlargeType.U1, loading)
    console.log("Enlarged U1 image: ", msg1)
    images.push(msg1.imageUrl);
    await sleep(3000)
    const msg2 = await client.imageEnlarge(baseimage.messageId, EnlargeType.U2, loading)
    console.log("Enlarged U2 image: ", msg2)
    images.push(msg2.imageUrl);
    await sleep(3000)
    const msg3 = await client.imageEnlarge(baseimage.messageId, EnlargeType.U3, loading)
    console.log("Enlarged U3 image: ", msg3)
    images.push(msg3.imageUrl);
    await sleep(3000)
    const msg4 = await client.imageEnlarge(baseimage.messageId, EnlargeType.U4, loading)
    console.log("Enlarged U4 image: ", msg4)
    images.push(msg4.imageUrl);
    console.log("done");
    return images
}
(async () => {
    await login();
    app.listen(3005, '0.0.0.0' , () => {
      console.log("Server running on port 3005");
    });
})();

app.post("/imagine", async (req, res) => {
  const prompt = req.body.prompt;

  if (!prompt) {
    return res.status(400).send("Missing prompt");
  }

  try {
    let images = await execute(prompt);
    console.log(images);
    res.json({ images });//send(images);
  } catch (error) {
    res.status(500).send("Internal Server Error");
  }
});`

**Comment by Draym** [comment]
i will check it out with your code.

@akwin1234 also please make sure to don't copy paste out your discord password.

**Comment by akwin1234** [comment]
> i will check it out with your code.
> 
> @akwin1234 also please make sure to don't copy paste out your discord password.

My bad sorry! In short having problem when trying to upscale all U1 to U4 images in row

**Comment by jasoncslaughter** [comment]
Yes, upscale no longer works with this library. Probably a change in how Slack structures the dom, so that the puppeteer code no longer works.

**Comment by Draym** [comment]
are you both using a free or premium account for midjourney ?

**Comment by jasoncslaughter** [comment]
Premium for myself, and I have plenty of time available.

**Comment by akwin1234** [comment]
i am using premium too @Draym

**Comment by jasoncslaughter** [comment]
The library went back to working for a while and now doesn't seem to work to upscale images at all again. 

One thing I noticed: It doesn't seem to be able to identify the message as complete in order to know it is OK to upscale. I noticed in this line: 

```return it != null && it.endsWith(".png") && it !== parentUrl;```

I think there is an issue with ```it.endsWith(".png")```, in that the image no longer ends with .png, looks like it has URL params appended at the end of the string.

**Comment by jasoncslaughter** [comment]
Yes, as a followup, I had time to test a fix.

I replaced `it.endsWith(".png")` with `it.includes(".png")` in the code, and now it seems to be working. I will try to submit a PR on Sunday when I have some time if no-one does it before then.

**Comment by Draym** [comment]
@jasoncslaughter fix included in latest version [@d-lab/discord-puppet@0.6.7](https://www.npmjs.com/package/@d-lab/discord-puppet/v/0.6.7)

**Comment by jasoncslaughter** [comment]
Awesome Draym - Thank you so much for fixing that!

**Comment by jasoncslaughter** [comment]
@Draym I might be missing something, but when installing the latest version via npm (and confirming via package.json), the `midjourney.puppet.js` in `dist` still uses `it.endsWith(".png")`.

**Comment by Draym** [comment]
@jasoncslaughter strange, i had run `tsc && npm publish`. maybe it's due to webstorm when using pre-defined runner.

i redeployed it [@d-lab/discord-puppet@0.6.8](https://www.npmjs.com/package/@d-lab/discord-puppet/v/0.6.8). Let me know if it fixes your issue.

**Comment by jasoncslaughter** [comment]
@Draym 

The new deployment fixes the issue with endsWith / includes. However, there is an issue where all upscale. Here is some code:

```
import {
  MidjourneyPuppet,
  options,
  Option,
  EnlargeType,
} from "@d-lab/discord-puppet";

(async () => {
  const config: Option = options(email, password);
  const puppet = new MidjourneyPuppet(config);
  await puppet.start();
  await puppet.clickServer(server);
  await puppet.clickChannel(channel);

  const msg = await puppet.imagine("happy kitten");
  for (let z = 1; z < 5; z++) {
    const enlargeType: EnlargeType = `U${z}` as EnlargeType;
    const subImage = await puppet.imageEnlarge(msg.messageId, enlargeType);
    console.log("subImage.imageUrl!", subImage.imageUrl!);
  }

  await puppet.shutdown();
})();
```

In the code, it imagines an image, then it iterates from 1 to 4, enlarging the image via U1 - U4, and outputs the URL of the enlarged image.

You will see that U1 - U4 always returns the same image (U1).
